- package-lock.json
- src/app-definition.type.ts
- src/commands/index.ts
- src/commands/logs.command.ts
- src/commands/restart.command.ts
- src/commands/shutdown.command.ts
- src/commands/start.command.ts
- src/commands/status.command.ts
- src/ecosystem.config.ts
- src/index.ts
> Refactor: extract commands

- package-lock.json
- package.json
- src/commands/start.command.ts
Depends on #3 
Formatted output for all commands and status table
> Feat: Formatted cli output

- README.md
- src/index.ts
> Feat: Add stop command

- README.md
- src/commands/start.command.ts
- src/script-definition.type.ts
@nsams I'm not sure if this is a better wording
> Refactor: Rename apps to scripts

- .husky/pre-commit
- CHANGELOG.md
- README.md
- package.json
- src/commands/start.command.ts
- src/index.ts
- yarn.lock
> Feat: only flag

- .husky/pre-commit
- CHANGELOG.md
- README.md
- package.json
- src/commands/start.command.ts
- src/index.ts
- src/script-definition.type.ts
- yarn.lock
depends on #17
this allows annotating scripts with groups and starting group of scripts
I will add Changelogs and Docs later as there is more planned
> Add group flag

- .husky/pre-commit
- CHANGELOG.md
- README.md
- package.json
- src/commands/start.command.ts
- src/daemon-command/logs.daemon-command.ts
- src/daemon-command/restart.daemon-command.ts
- src/daemon-command/shutdown.daemon-command.ts
- src/daemon-command/shutdown.ts
- src/daemon-command/start-process.ts
- src/daemon-command/status.daemon-command.ts
- src/index.ts
- src/script-definition.type.ts
- yarn.lock
depends on #18
Previously this was all in start.command.ts
> Refactor daemon commands into own function and file

- .husky/pre-commit
- CHANGELOG.md
- README.md
- example/dev-pm.config.js
- package.json
- src/commands/auto-start-deamon.ts
- src/commands/restart.command.ts
- src/commands/shutdown.command.ts
- src/commands/start-daemon.command.ts
- src/commands/start.command.ts
- src/commands/status.command.ts
- src/commands/stop.command.ts
- src/daemon-command/kill-process.ts
- src/daemon-command/logs.daemon-command.ts
- src/daemon-command/restart.daemon-command.ts
- src/daemon-command/shutdown.daemon-command.ts
- src/daemon-command/shutdown.ts
- src/daemon-command/start-process.ts
- src/daemon-command/start.deamon-command.ts
- src/daemon-command/status.daemon-command.ts
- src/daemon-command/stop.daemon-command.ts
- src/index.ts
- src/script-definition.type.ts
- yarn.lock
depends on #20 
- stop command renamed to shutdown
- new command stop that stops a single script
> Make individual scripts stoppable

- CHANGELOG.md
- README.md
- example/dev-pm.config.js
- src/commands/restart.command.ts
- src/commands/start-daemon.command.ts
- src/commands/start.command.ts
- src/commands/status.command.ts
- src/commands/stop.command.ts
- src/daemon-command/logs.daemon-command.ts
- src/daemon-command/restart.daemon-command.ts
- src/daemon-command/scripts-matching-pattern.ts
- src/daemon-command/start.deamon-command.ts
- src/daemon-command/status.daemon-command.ts
- src/daemon-command/stop.daemon-command.ts
- src/index.ts
> Remove start options and replace them by a name argument that works the same for all commands

- .husky/pre-commit
- CHANGELOG.md
- README.md
- example/dev-pm.config.js
- package.json
- src/commands/auto-start-deamon.ts
- src/commands/restart.command.ts
- src/commands/shutdown.command.ts
- src/commands/start-daemon.command.ts
- src/commands/start.command.ts
- src/commands/status.command.ts
- src/commands/stop.command.ts
- src/daemon-command/kill-process.ts
- src/daemon-command/logs.daemon-command.ts
- src/daemon-command/restart.daemon-command.ts
- src/daemon-command/scripts-matching-pattern.ts
- src/daemon-command/shutdown.daemon-command.ts
- src/daemon-command/shutdown.ts
- src/daemon-command/start-process.ts
- src/daemon-command/start.deamon-command.ts
- src/daemon-command/status.daemon-command.ts
- src/daemon-command/stop.daemon-command.ts
- src/index.ts
- src/script-definition.type.ts
- yarn.lock
> buffer 100 lines of logs for each process to show on logs command

- CHANGELOG.md
- README.md
- src/commands/connect.ts
- src/commands/logs.command.ts
- src/commands/restart.command.ts
- src/commands/shutdown.command.ts
- src/commands/start.command.ts
- src/commands/status.command.ts
- src/commands/stop.command.ts
- src/daemon-command/logs.daemon-command.ts
- src/daemon-command/restart.daemon-command.ts
- src/daemon-command/script.ts
- src/daemon-command/start.deamon-command.ts
- src/index.ts
> Add --follow option to start/restart command to follow logs after start

- CHANGELOG.md
- README.md
- package.json
- src/commands/status.command.ts
- src/daemon-command/status.daemon-command.ts
- src/index.ts
- yarn.lock
depends on #32
I'm not sure about the name of this option
> Add refresh option to status - Keep status open and refresh periodically

- src/commands/start-daemon.command.ts
we should not shutdown with a very good reason
> Remove shutdown on various events, this was mainly for debugging

- src/daemon-command/restart.daemon-command.ts
- src/daemon-command/script.ts
- src/daemon-command/shutdown.ts
- src/daemon-command/status.daemon-command.ts
- src/daemon-command/stop.daemon-command.ts
> Show restart count in status

- CHANGELOG.md
- package.json
- Set version number in package.json
- Specify date in changelog
> Prepare 2.0.0 release

- src/index.ts
I just wanted to check the used version but failed to do so...
> Add version number that commander will output for --version

- .changeset/silver-wolves-flow.md
- src/commands/logs.command.ts
- src/commands/start-daemon.command.ts
- src/commands/stop.command.ts
- src/daemon-command/logs.daemon-command.ts
- src/daemon-command/restart.daemon-command.ts
- src/daemon-command/script.ts
- src/daemon-command/scripts-matching-pattern.ts
- src/daemon-command/start.daemon-command.ts
- src/daemon-command/status.daemon-command.ts
- src/daemon-command/stop.daemon-command.ts
- src/index.ts
- src/script-definition.type.ts
```
dev-pm status
┌────┬─────────┬─────────┬─────┬─────────┬───────┬──────────┐
│ ID │ Script  │ Status  │ CPU │ Mem     │ PID   │ Restarts │
├────┼─────────┼─────────┼─────┼─────────┼───────┼──────────┤
│ 0  │ sleep-1 │ Running │ 0%  │ 5.24 MB │ 72556 │ 0        │
│ 1  │ sleep-2 │ Running │ 0%  │ 5.24 MB │ 72628 │ 0        │
└────┴─────────┴─────────┴─────┴─────────┴───────┴──────────┘
dev-pm status 1
┌────┬─────────┬─────────┬─────┬─────────┬───────┬──────────┐
│ ID │ Script  │ Status  │ CPU │ Mem     │ PID   │ Restarts │
├────┼─────────┼─────────┼─────┼─────────┼───────┼──────────┤
│ 1  │ sleep-2 │ Running │ 0%  │ 5.24 MB │ 72628 │ 0        │
└────┴─────────┴─────────┴─────┴─────────┴───────┴──────────┘
```
> feat: every script is now accessible through an dedicated numeric id

- .changeset/weak-pants-buy.md
- example/dev-pm.config.js
- src/commands/start-daemon.command.ts
- src/config.type.ts
- src/index.ts
Can be used to type check the configuration file.
> Expose config type

- .github/workflows/release-canary.yml
- .github/workflows/release.yml
- package.json
Changeset doesn't understand `&&`. 🙄
> Fix publish script

- .husky/pre-commit
Fixes forgotten breaking change
> Fix: Husky hook after upgrade

- renovate.json
Copy relevant parts from core config: https://github.com/vivid-planet/comet/blob/main/renovate.json.
> Renovate: tweak config
