vivid-planet/dev-process-manager

.husky/pre-commit, CHANGELOG.md, README.md, package.json, src/commands/auto-start-deamon.ts, src/commands/start-daemon.command.ts, src/commands/start.command.ts, src/daemon-command/logs.daemon-command.ts, src/daemon-command/restart.daemon-command.ts, src/daemon-command/shutdown.daemon-command.ts, src/daemon-command/shutdown.ts, src/daemon-command/start-process.ts, src/daemon-command/start.deamon-command.ts, src/daemon-command/status.daemon-command.ts, src/index.ts, src/script-definition.type.ts, yarn.lock
depends on #19 
start now also connects to the deamon
this allows multiple calls to start that start different scripts
start-daemon is started as background process in start (if not yet running)
Major (incompatible) changes:
- start is not blocking anymore (and doesn't show logs anymore)
- changing pm config file isn't possible anymore
=> Add a start-deamon command that only starts the daemon (instead of start)

src/daemon-command/handle-log-socket-close.ts, src/daemon-command/logs.daemon-command.ts, src/daemon-command/restart.daemon-command.ts, src/daemon-command/script.ts, src/daemon-command/start.daemon-command.ts
fixes warning 'MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit' when more than 10 scripts exist
=> Fix event listener warning by not subscriping close for every script

src/daemon-command/status.daemon-command.ts
fixes error 'This socket has been ended by the other party'
=> End interactive status when socket is closed (destroyed)

src/commands/start-daemon.command.ts
Leaving child processes running will result in blocked ports and other issues, so if the daemon crashes it should try to kill them too.
=> partially revert #36, it did have it's use to kill child processes when daemon process exits

src/daemon-command/script.ts
New lines where inserted one line too early, so the first line was always displayed last
=> Fix: Log buffer

CHANGELOG.md, package.json, src/index.ts, yarn.lock
Currently `waitOn: ["tcp:$POSTGRESQL_PORT"]` only works when POSTGRESQL_PORT is in the env, but not if only in .env.
As a workaround you an use `dotenv -- dev-pm start` which is fine as script in package.json but very inconvenient when using dev-pm directly. (the first call that stats the daemon needs the env!)
With this change we remove the need for dotenv usage outside completely.
=> Add support for .env files using dotenv

CHANGELOG.md, package.json
Currently this package produces warnings when e.g. used with node18 or npm
---------
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@comet/dev-process-manager@2.1.0',
npm WARN EBADENGINE   required: { node: '14', yarn: '3' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '7.19.1' }
npm WARN EBADENGINE }
````
=> Make engine configuration less strict

CHANGELOG.md, src/index.ts
status and shutdown are such long words. Therefore, I suggest adding the shortcuts `list` and `ls` (for `status`) and `kill` (for `shutdown`).
=> Add aliases for status and shutdown

src/daemon-command/script.ts
`npm bin` was used to generate the path to the local .bin directory. NPM v9 removed the bin command (https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/). Now use `npm root` to generate the path.
=> Make compatible with NPM 9

.github/workflows/release-canary.yml, .github/workflows/release.yml
also mentioned here: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages changesets/action docs use NPM_TOKEN tough
I don't know the difference.
=> Use NODE_AUTH_TOKEN env as it was before to fix canary release

.changeset/stale-tables-sleep.md, package.json, yarn.lock
`@changesets/cli` was incorrectly added to the package's dependencies, causing it to be installed when installing dev-pm in a project. We move it to the dev dependencies to fix it.
=> Remove changesets dependency

.changeset/grumpy-peaches-hang.md, src/daemon-command/script.ts
It's annoying restarting crashed services in development manually because waiting 30s is just too long.
=> Change backoff-time to 10s

.changeset/rude-kiwis-flash.md, src/daemon-command/scripts-matching-pattern.ts
The change in #79 introduced a bug where matching via groups wouldn't work anymore. The group name was incorrectly checked for the first character of the name, which is always "@". To fix this, we correctly extract the group name from the pattern.
=> Fix script matching via groups

.github/workflows/release-canary.yml, .github/workflows/release.yml, package.json
Apparently, NPM calls the publish script when running `npm publish`, resulting in trying to publish the same package twice. We remove the publish script in an attempt to fix it.
See https://stackoverflow.com/questions/71730319/npm-attempts-to-publish-twice for more information.
=> Fix canary release

package.json, yarn.lock
From version 6 pretty-bytes is ESM only. This did not work.
=> Chore: Downgrade pretty-bytes

.changeset/chilled-wombats-count.md, src/daemon-command/script.ts, src/index.ts
This can cause problems when the child process has a custom .env loading mechanism (eg. additional files such as .env.secrets) but dev-pm sets env vars which overrule the values loaded from .env by child child process
=> Don't inject .env file as real env variables for child processes

.changeset/spotty-mirrors-care.md, src/commands/start-daemon.command.ts, src/daemon-command/script.ts
This allows modifications without having to shutdown the deamon.
- processes are not restarted if the script command changes
- processes are stopped if the script is removed
- processes are not started if a new script is added
- identifier for updates is the name of a script
=> Watch dev-pm.config.js and update in running daemon

.changeset/giant-boats-suffer.md, package.json, src/commands/auto-start-daemon.ts, src/commands/connect.ts, src/commands/index.ts, src/commands/logs.command.ts, src/commands/restart.command.ts, src/commands/shutdown.command.ts, src/commands/start-daemon.command.ts, src/commands/start.command.ts, src/commands/status.command.ts, src/commands/stop.command.ts, src/config.type.ts, src/daemon-command/handle-log-socket-close.ts, src/daemon-command/logs.daemon-command.ts, src/daemon-command/restart.daemon-command.ts, src/daemon-command/script.ts, src/daemon-command/scripts-matching-pattern.ts, src/daemon-command/shutdown.daemon-command.ts, src/daemon-command/shutdown.ts, src/daemon-command/start.daemon-command.ts, src/daemon-command/status.daemon-command.ts, src/daemon-command/stop.daemon-command.ts, src/dev-pm.ts, src/index.ts, tsconfig.json
Convert this package to ESM
- the bin script dev-pm is not affected by this internal change
- the only public api is the exported Config type: I did a quick test by copying the package into comet, types where resolved correctly
This is done in preparation for https://github.com/vivid-planet/dev-process-manager/pull/106, so we can use unconfig, which is ESM-only.
=> Convert to ESM

.changeset/many-masks-flow.md, src/daemon-command/logs.daemon-command.ts, src/daemon-command/restart.daemon-command.ts, src/daemon-command/status.daemon-command.ts, src/daemon-command/stop.daemon-command.ts
Maybe this fixes the problem that no error is shown on mac
=> Add missing newline to 'no matching scripts' error

.changeset/light-lions-destroy.md, src/commands/logs.command.ts, src/commands/restart.command.ts, src/commands/shutdown.command.ts, src/commands/start.command.ts, src/commands/status.command.ts, src/commands/stop.command.ts, src/commands/validate-config.ts, src/utils/load-config.ts
Before the start-daemon background process crashed on invalid config (eg when `export default` is forgotten) showing no error in eg. `dpm status`. Now the config is validated before trying to start the background process and a nice error is shown.
example output:
```
niko@niko:~/dev/dev-process-manager/example validate-config$ node ../lib/dev-pm.js start
dev-pm.config doesn't export a config object, make sure to add a default export
niko@niko:~/dev/dev-process-manager/example validate-config$ cd ../example2/
niko@niko:~/dev/dev-process-manager/example2 validate-config$ node ../lib/dev-pm.js start
dev-pm.config file not found
```
=> Show a nice console error when config is invalid

src/daemon-command/start.daemon-command.ts
The fix from https://github.com/vivid-planet/dev-process-manager/pull/115 works on macOS, but was forgotten in one case.
=> Add missing newline to 'no matching scripts' error (for real)
